version: "3.9"

services:
  automation:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Browser execution mode: true (headless) or false (headed)
      - HEADLESS=true
      # Target environment: dev, stage, prod
      - ENV=stage
      # Environment-specific URLs
      - STAGE_URL=https://stage.wiseai.wiseyak.com/login
    volumes:
      - ./reports:/app/reports
    working_dir: /app
    command: pytest tests/tests_login.py
    tty: true
    stdin_open: true
